name: wiki_flutter_examples
description: "Wiki for Flutter Widgets"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  fl_chart: ^0.66.0
  provider: ^6.1.1
  flutter_native_splash: ^2.3.9
  sign_in_with_apple: ^5.0.0
  http: ^1.2.0
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  video_player: ^2.8.2
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  simple_animations: ^5.0.2
  get: ^4.6.5
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  google_sign_in: ^5.4.4
  font_awesome_flutter: ^10.3.0
  flutter_svg: ^1.1.5
  pinput: ^2.2.18
  readmore: ^2.1.0
  shared_preferences: ^2.0.16
  flutter_image_slideshow: ^0.1.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/mountains.jpg
    - images/milkyway.jpg
    - images/angry_dog.png
    - images/panda.png
    - images/cloning/spotify/
    - images/cloning/spotify/home/
    - images/cloning/spotify/artists/
    - images/cloning/spotify/podcasts/
    - images/cloning/spotify/2010/
    - images/cloning/spotify/drake mix/
    - images/cloning/spotify/upbeat/
    - images/cloning/spotify/chill/
    - images/cloning/nike/
    - assets/video/
    - assets/shoeappui/images/
    - assets/shoeappui/images/coloroptions/
    - assets/shoeappui/files/

  fonts:
    - family: AM
      fonts:
        - asset: assets/fonts/Avenir Medium.ttf

    - family: AB
      fonts:
        - asset: assets/fonts/Avenir Next LT Pro Bold.otf

    - family: PoiretOne
      fonts:
        - asset: assets/shoeappui/fonts/PoiretOne-Regular.ttf

    - family: Questrial
      fonts:
        - asset: assets/shoeappui/fonts/Questrial-Regular.ttf

flutter_native_splash:
  color: "#42a5f5"